home: https://icmoc.com
social:
  linkedin: https://www.linkedin.com
  facebook: https://facebook.com
  twitter: https://twitter.com
  crunchbase: https://crunchbase.com
  instagram: https://instagram.com
  github: https://github.com
contact_email: mailto:encore.shao@gmail.com
